version = 0.1

[default.global.parameters]
stack_name = "auto-haaland"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
resolve_image_repos = true

[dev]
[dev.deploy.parameters]
stack_name = "auto-haaland-dev"
region = "ap-southeast-2"
parameter_overrides = "Environment=dev CorsAllowOrigin=*"
confirm_changeset = false
resolve_s3 = true
resolve_image_repos = true
capabilities = "CAPABILITY_IAM"
tags = "Project=auto-haaland Environment=dev"

[prod]
[prod.deploy.parameters]
stack_name = "auto-haaland-prod"
region = "ap-southeast-2"
parameter_overrides = "Environment=prod CorsAllowOrigin=https://juane98.github.io"
confirm_changeset = true
resolve_s3 = true
resolve_image_repos = true
capabilities = "CAPABILITY_IAM"
tags = "Project=auto-haaland Environment=prod"
